---
development:
  adapter: postgresql
  database: guess_the_intro_development
  host: localhost
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: guess_the_intro_test
  host: localhost
  pool: 5
  timeout: 5000
